import { useDispatch, useSelector }from "react-redux";
import './TextInput.css';

export default function TextInput() {

    // hook returns function to send update requests to store
    const dispatch = useDispatch();

    // get current state of inputText from store
    const text = useSelector(state => state.inputText);

    // typed characters are sent to store as actions (update requests) via the dispatch function
    const handleChange = (event) => {
        // store forwards action to reducer who builds new state
        dispatch ({
            type: "SET_INPUT_TEXT",
            payload: event.target.value
        });
      }
    
    return (
        <div>
            {/* user typing triggers handleChange function for each character */}
            {/* text in field is generated by reading inputText from store */}
            {/* field doesn't show what user typed, but rather the state of textInput in store */}
            {/* if dispatch() is used, all useSelectors are informed of a new state and run again -> subscription mechanism */}
            <input className="NiceInput" type="text" onChange={handleChange} value={text}/>
        </div>
    );
}
